"""Audit dataset/full references (" ".join(docstring_tokens)) for noise."""
import json, re, sys, collections

FILES = ["dataset/full/test.jsonl", "dataset/full/train.jsonl"]

URL_RE = re.compile(r"https?://|www\.")
HTML_RE = re.compile(r"</?(p|br|pre|code|ul|li|b|i|a|tt|em)\b[^>]*>", re.I)
JAVADOC_TAG_RE = re.compile(r"@(param|return|throws|see|link|inheritDoc|deprecated|since|author)", re.I)
NONASCII_RE = re.compile(r"[^\x00-\x7f]")
CJK_RE = re.compile(r"[぀-ヿ一-鿿가-힯]")
CODEY_RE = re.compile(r"(^|\s)(def \w|import \w|public (static|void|class)|\{|\}|;\s*$|==|=>|\w+\(\)\s*;|^r?[\\\[]|\*/|/\*\*)")
BOILER_RE = re.compile(
    r"(\b(todo|fixme|xxx+)\b[:\s]|auto-?generated|generated by (this|the)?|do not (edit|modify)|"
    r"non-?javadoc|inheritdoc|created by \w+ on|copyright \(c\)|licensed under|apache license|"
    r"not implemented|see above|see below|^ditto|^same as|^placeholder|^n/?a\s*$|^\.+$)", re.I)
CONSTRUCTOR_RE = re.compile(r"^(constructor|ctor|default constructor|creates? a new instance|instantiates a new)\b", re.I)


def word_set(s):
    return set(re.findall(r"[a-z]+", s.lower()))


def split_ident(name):
    name = name.split(".")[-1]
    parts = re.split(r"[_\W]+", re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", name))
    return {p.lower() for p in parts if p}


def check(r):
    ref = " ".join(r["docstring_tokens"]).strip()
    toks = r["docstring_tokens"]
    issues = []
    if not ref:
        issues.append("empty")
        return ref, issues
    nw = len(toks)
    if nw <= 2:
        issues.append("too_short(<=2 tok)")
    if nw > 60:
        issues.append("too_long(>60 tok)")
    if URL_RE.search(ref):
        issues.append("url")
    if HTML_RE.search(ref):
        issues.append("html")
    if JAVADOC_TAG_RE.search(ref):
        issues.append("javadoc_tags")
    if CJK_RE.search(ref):
        issues.append("non_english_cjk")
    elif NONASCII_RE.search(ref):
        issues.append("non_ascii")
    if CODEY_RE.search(ref):
        issues.append("code_like")
    if BOILER_RE.search(ref):
        issues.append("boilerplate")
    if CONSTRUCTOR_RE.match(ref):
        issues.append("trivial_constructor")
    # ref is just the function name restated
    fw = split_ident(r["func_name"])
    rw = word_set(ref)
    if rw and fw and rw <= fw:
        issues.append("restates_func_name")
    letters = sum(c.isalpha() for c in ref)
    if letters / max(len(ref), 1) < 0.5:
        issues.append("low_alpha_ratio")
    if not re.search(r"[A-Za-z]{3}", ref):
        issues.append("no_real_words")
    return ref, issues


def main():
    for path in FILES:
        rows = [json.loads(l) for l in open(path)]
        counts = collections.Counter()
        flagged = []
        dupes = collections.Counter(" ".join(r["docstring_tokens"]).strip().lower() for r in rows)
        for r in rows:
            ref, issues = check(r)
            if dupes[ref.lower()] >= 5:
                issues.append(f"duplicated(x{dupes[ref.lower()]})")
            if issues:
                counts.update(issues)
                flagged.append((r, ref, issues))
        print("=" * 80)
        print(f"{path}: {len(rows)} rows, {len(flagged)} flagged ({len(flagged)/len(rows):.1%})")
        by_lang = collections.Counter(r["language"] for r, _, _ in flagged)
        print("  flagged by language:", dict(by_lang))
        for k, v in counts.most_common():
            print(f"  {k:28s} {v:5d}  ({v/len(rows):.1%})")
        # examples
        print("\n  --- examples ---")
        seen = collections.Counter()
        for r, ref, issues in flagged:
            key = issues[0]
            if seen[key] >= 3:
                continue
            seen[key] += 1
            print(f"  [{','.join(issues)}] {r['language']} {r['func_name']}")
            print(f"      {ref[:200]!r}")
        json.dump(
            [{"id": r["id"], "lang": r["language"], "func": r["func_name"], "repo": r["repo"],
              "ref": ref, "issues": iss} for r, ref, iss in flagged],
            open(f"/tmp/claude-1000/-home-phuc-code-sum/0783430b-cc3d-4369-b785-e9e69a015082/scratchpad/flagged_{path.split('/')[-1].split('.')[0]}.json", "w"),
            indent=1)


main()
